"""Add check constraint on user role

Revision ID: c5e4d7e6d8dc
Revises: b0a90a242c83
Create Date: 2025-03-06 14:28:10.936574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e4d7e6d8dc'
down_revision: Union[str, None] = 'b0a90a242c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
